<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>

    <!-- Self-contained Windows build -->
    <SelfContained>false</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>

    <RootNamespace>Winlink_Checkins</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Company>KB7WHO, Kenneth Burton</Company>
    <Product>Winlink_Checkins</Product>
    <AssemblyTitle>Winlink_Checkins</AssemblyTitle>
    <ApplicationIcon>check.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Core" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.72.0.3966" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="check.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="credentials.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
	
	<Content Include="roster.txt">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
	
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
